# Generated by Django 5.0.2 on 2024-02-24 13:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('post_image', models.ImageField(upload_to='post_image')),
                ('date_to_cteate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_to_create', models.DateTimeField(default=datetime.datetime.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.article')),
            ],
        ),
    ]
